version: '3'
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php_container
    volumes:
      - ./app:/var/www

  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d  

  mysql_db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    container_name: mysql_container
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql
